// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-learning-os/AudioMobile.tsx": () => import("../components/mockups/ai-learning-os/AudioMobile.tsx"),
  "./components/mockups/ai-learning-os/CertificatesDesktop.tsx": () => import("../components/mockups/ai-learning-os/CertificatesDesktop.tsx"),
  "./components/mockups/ai-learning-os/ChallengeMobile.tsx": () => import("../components/mockups/ai-learning-os/ChallengeMobile.tsx"),
  "./components/mockups/ai-learning-os/DashboardDesktop.tsx": () => import("../components/mockups/ai-learning-os/DashboardDesktop.tsx"),
  "./components/mockups/ai-learning-os/FinalMobileApp.tsx": () => import("../components/mockups/ai-learning-os/FinalMobileApp.tsx"),
  "./components/mockups/ai-learning-os/FinalWebApp.tsx": () => import("../components/mockups/ai-learning-os/FinalWebApp.tsx"),
  "./components/mockups/ai-learning-os/PlaygroundDesktop.tsx": () => import("../components/mockups/ai-learning-os/PlaygroundDesktop.tsx")
};
